// JUST FOR THE FIRST SUGGESTION AND QUICK ANSWER SECTION

function getLocation() {
    navigator.geolocation.getCurrentPosition(showPosition);
}

function showPosition(position) {
quick.innerHTML = "<b>Galaxy found " + text.split(" near me")[0] + " near you.</b><br>See all locations in maps.<br><br><img src='https://upload.wikimedia.org/wikipedia/commons/d/dc/Google_Maps_Logo.svg' style='width:100%; border-radius:8px;'><br><a href='https://www.google.com/maps/search/" + text.split(" near me")[0] + "/@" + position.coords.latitude + "," + position.coords.longitude + "' target='_blank'>maps.google.com</a>";
first.innerHTML = text.split(" near me")[0] + " near you - Google Maps<br><a href='https://www.google.com/maps/search/" + text.split(" near me")[0] + "/@" + position.coords.latitude + "," + position.coords.longitude + "' target='_blank'>maps.google.com</a>";
}

function setquickAnswer() {
var query = location.search.split("=")[1].split("&")[0].replace(/\+/gi, " ");
var first = document.getElementById("first");
var quick = document.getElementById("quick");
var text = query.toLowerCase();


if (query == "teabag") {
first.innerHTML = "TeaBag - brewing virtual tea<br><a href='https://lb123658.github.io/tea' target='blank'><button style='background:grey; border:none; font-size:18px; cursor:pointer; padding:5px; margin:5px; border-radius: 5px; margin-left:0px;'>TeaBag game official site | Play Now</button><br>lb123658.github.io</a>";
quick.innerHTML = "<b>TeaBag - video game</b><br><p>TeaBag is a free online game that brings virtual tea to your computer. Brew virtual tea, buy new teapots, cups, and tea varieties, while collecting points and money to upgrade your supplies. Creating a TeaBag account is free.</p><br><a href='https://lb123658.github.io/tea' target='blank'>lb123658.github.io</a>";
quick.style.visibility = "visible";
} else if (text == "google") {
first.innerHTML = "Google<br><a href='https://www.google.com' target='blank'>www.google.com</a>";
quick.innerHTML = "<b>Google - technology company</b><br><br><img src='https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg' style='width:100%;'><br><p>Google LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware.</p><br><a href='https://www.google.com' target='blank'>www.google.com</a>";
quick.style.visibility = "visible";
} else if (text == "yahoo") {
first.innerHTML = "Yahoo<br><a href='https://www.yahoo.com' target='blank'>www.yahoo.com</a>";
quick.innerHTML = "<b>Yahoo - web portal</b><br><br><img src='https://upload.wikimedia.org/wikipedia/commons/3/3a/Yahoo%21_%282019%29.svg' style='width:100%;'><br><p>Yahoo is an American web services provider. It is headquartered in Sunnyvale, California and is owned by Verizon Media, pending sale to investment funds managed by Apollo Global Management.It provides a web portal, search engine Yahoo Search, and related services, including My Yahoo!, Yahoo Mail, Yahoo News, Yahoo Finance, Yahoo Sports and its advertising platform, Verizon Media Native.</p><br><a href='https://www.yahoo.com' target='blank'>www.yahoo.com</a>";
quick.style.visibility = "visible";
} else if (text == "netflix") {
first.innerHTML = "Netflix - Watch TV Shows Online, Watch Movies Online<br><a href='https://www.netflix.com' target='blank'>www.netflix.com</a>";
quick.innerHTML = "<b>Netflix - streaming service</b><br><br><img src='https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg' style='width:100%;'><br><p>Netflix, Inc. is an American over-the-top content platform and production company headquartered in Los Gatos, California. Netflix was founded in 1997 by Reed Hastings and Marc Randolph in Scotts Valley, California. The company's primary business is a subscription-based streaming service offering online streaming from a library of films and television series, including those produced in-house. As of July 2021, Netflix had 209 million subscribers, including 72 million in the United States and Canada. It is available worldwide except in mainland China (due to local restrictions), Syria, North Korea, and Crimea (due to US sanctions). The company has offices in Canada, France, Brazil, the Netherlands, India, Japan, South Korea, and the United Kingdom. Netflix is a member of the Motion Picture Association (MPA), producing and distributing content from countries all over the globe.</p><br><a href='https://www.netflix.com' target='blank'>www.netflix.com</a>";
quick.style.visibility = "visible";
} else if (text == "discord") {
first.innerHTML = "Discord | Your Place to Talk and Hang Out<br><a href='https://discord.com' target='blank'>discord.com</a>";
quick.innerHTML = "<b>Discord - instant messaging</b><br><br><img src='https://upload.wikimedia.org/wikipedia/en/9/98/Discord_logo.svg' style='width:100%;'><br><p>Discord is an instant messaging and digital distribution platform designed for creating communities. Users communicate with voice calls, video calls, text messaging, media and files in private chats or as part of communities called servers. Servers are a collection of persistent chat rooms and voice chat channels. Discord runs on Windows, macOS, Android, iOS, iPadOS, Linux, and in web browsers. As of December 2020, the service has over 250 million registered users and over 140 million monthly active users.</p><br><a href='https://discord.com' target='blank'>discord.com</a>";
quick.style.visibility = "visible";
} else if (text == "whatsapp") {
first.innerHTML = "WhatsApp<br><a href='https://www.whatsapp.com' target='blank'>www.whatsapp.com</a>";
quick.innerHTML = "<b>WhatsApp - messaging platform</b><br><br><img src='https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg' style='width:100%;'><br><p>WhatsApp Messenger, or simply WhatsApp, is an American freeware, cross-platform centralized messaging and voice-over-IP service owned by Facebook, Inc. It allows users to send text messages and voice messages, make voice and video calls, and share images, documents, user locations, and other content. WhatsApp's client application runs on mobile devices but is also accessible from desktop computers, as long as the user's mobile device remains connected to the Internet while they use the desktop app. The service requires a cellular mobile telephone number to sign up.</p><br><a href='https://www.whatsapp.com' target='blank'>www.whatsapp.com</a>";
quick.style.visibility = "visible";
} else if (text == "whatsapp web") {
first.innerHTML = "WhatsApp<br><a href='https://www.whatsapp.com' target='blank'>www.whatsapp.com</a>";
quick.innerHTML = "<b>WhatsApp - messaging platform</b><br><br><img src='https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg' style='width:100%;'><br><p>WhatsApp Messenger, or simply WhatsApp, is an American freeware, cross-platform centralized messaging and voice-over-IP service owned by Facebook, Inc. It allows users to send text messages and voice messages, make voice and video calls, and share images, documents, user locations, and other content. WhatsApp's client application runs on mobile devices but is also accessible from desktop computers, as long as the user's mobile device remains connected to the Internet while they use the desktop app. The service requires a cellular mobile telephone number to sign up.</p><br><a href='https://www.whatsapp.com' target='blank'>www.whatsapp.com</a>";
quick.style.visibility = "visible";
} else if (text == "youtube") {
first.innerHTML = "YouTube<br><a href='https://www.youtube.com' target='blank'>www.youtube.com</a>";
quick.innerHTML = "<b>YouTube - video sharing company</b><br><br><img src='https://upload.wikimedia.org/wikipedia/commons/b/b8/YouTube_Logo_2017.svg' style='width:100%;'><br><p>YouTube is an American online video sharing and social media platform launched by Steve Chen, Chad Hurley, and Jawed Karim in February 2005. Its users watch more than one billion hours of videos each day.</p><br><a href='https://www.youtube.com' target='blank'>www.youtube.com</a>";
quick.style.visibility = "visible";
} else if (text == "facebook") {
first.innerHTML = "Facebook<br><a href='https://www.facebook.com' target='blank'>www.facebook.com</a>";
quick.innerHTML = "<b>Facebook - social media</b><br><br><img src='https://upload.wikimedia.org/wikipedia/commons/8/89/Facebook_Logo_%282019%29.svg' style='width:100%;'><br><p>Facebook, Inc., is an American multinational conglomerate based in Menlo Park, California. It was founded by Mark Zuckerberg, along with his fellow roommates and students at Harvard College</p><br><a href='https://www.facebook.com' target='blank'>www.facebook.com</a>";
quick.style.visibility = "visible";
} else if (text == "gmail") {
first.innerHTML = "Gmail<br><a href='https://mail.google.com' target='blank'>mail.google.com</a>";
quick.innerHTML = "<b>Gmail - email service</b<br><br><img src='https://upload.wikimedia.org/wikipedia/commons/7/7e/Gmail_icon_%282020%29.svg' style='width:100%;'><br><p>Gmail is a free email service provided by Google. As of 2019, it had 1.5 billion active users worldwide. A user typically accesses Gmail in a web browser or the official mobile app. Google also supports the use of email clients via the POP and IMAP protocols.</p><br><a href='https://mail.google.com' target='blank'>mail.google.com</a>";
quick.style.visibility = "visible";
} else if (text == "amazon") {
first.innerHTML = "Amazon<br><a href='https://www.amazon.com' target='blank'>www.amazon.com</a>";
quick.innerHTML = "<b>Amazon - online store</b><br><br><img src='https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg' style='width:100%;'><br><p>Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence. It is one of the Big Five companies in the U.S. information technology industry, along with Google, Apple, Microsoft, and Facebook. </p><br><a href='https://www.amazon.com' target='blank'>www.amazon.com</a>";
quick.style.visibility = "visible";
} else if (text == "olympics") {
first.innerHTML = "2020 Tokyo Olympics<br><a href='https://olympics.com' target='blank'>olympics.com</a>";
quick.innerHTML = "<b>Olympic Games Tokyo 2020</b><br>July 23, 2021 - August 8, 2021<br><br><p>The 2020 Summer Olympics (Japanese: 2020年夏季オリンピック, Hepburn: Nisen Nijū-nen Kaki Orinpikku), officially the Games of the XXXII Olympiad (第三十二回オリンピック競技大会, Dai Sanjūni-kai Orinpikku Kyōgi Taikai) and branded as Tokyo 2020 (東京2020), is an ongoing international multi-sport event that is currently being held from 23 July to 8 August 2021 in Tokyo, Japan, with some preliminary events beginning on 21 July.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Olympic_rings_without_rims.svg/2880px-Olympic_rings_without_rims.svg.png' style='width:100%; border-radius:8px;'><br><a href='https://www.nbcolympics.com/' target='blank'>Watch on NBC</a><br><a href='https://olympics.com/' target='blank'>Olympics website</a><br><a href='https://www.google.com/search?q=Olympic+Games+Tokyo' target='blank'>More information</a>";
quick.style.visibility = "visible";
} else if (text == "tokyo olympics") {
first.innerHTML = "2020 Tokyo Olympics<br><a href='https://olympics.com' target='blank'>olympics.com</a>";
quick.innerHTML = "<b>Olympic Games Tokyo 2020</b><br>July 23, 2021 - August 8, 2021<br><br><p>The 2020 Summer Olympics (Japanese: 2020年夏季オリンピック, Hepburn: Nisen Nijū-nen Kaki Orinpikku), officially the Games of the XXXII Olympiad (第三十二回オリンピック競技大会, Dai Sanjūni-kai Orinpikku Kyōgi Taikai) and branded as Tokyo 2020 (東京2020), is an ongoing international multi-sport event that is currently being held from 23 July to 8 August 2021 in Tokyo, Japan, with some preliminary events beginning on 21 July.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Olympic_rings_without_rims.svg/2880px-Olympic_rings_without_rims.svg.png' style='width:100%; border-radius:8px;'><br><a href='https://www.nbcolympics.com/' target='blank'>Watch on NBC</a><br><a href='https://olympics.com/' target='blank'>Olympics website</a><br><a href='https://www.google.com/search?q=Olympic+Games+Tokyo' target='blank'>More information</a>";
quick.style.visibility = "visible";
} else if (text == "2020 olympics") {
first.innerHTML = "2020 Tokyo Olympics<br><a href='https://olympics.com' target='blank'>olympics.com</a>";
quick.innerHTML = "<b>Olympic Games Tokyo 2020</b><br>July 23, 2021 - August 8, 2021<br><br><p>The 2020 Summer Olympics (Japanese: 2020年夏季オリンピック, Hepburn: Nisen Nijū-nen Kaki Orinpikku), officially the Games of the XXXII Olympiad (第三十二回オリンピック競技大会, Dai Sanjūni-kai Orinpikku Kyōgi Taikai) and branded as Tokyo 2020 (東京2020), is an ongoing international multi-sport event that is currently being held from 23 July to 8 August 2021 in Tokyo, Japan, with some preliminary events beginning on 21 July.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Olympic_rings_without_rims.svg/2880px-Olympic_rings_without_rims.svg.png' style='width:100%; border-radius:8px;'><br><a href='https://www.nbcolympics.com/' target='blank'>Watch on NBC</a><br><a href='https://olympics.com/' target='blank'>Olympics website</a><br><a href='https://www.google.com/search?q=Olympic+Games+Tokyo' target='blank'>More information</a>";
quick.style.visibility = "visible";
} else if (text == " 2021 olympics") {
first.innerHTML = "2020 Tokyo Olympics<br><a href='https://olympics.com' target='blank'>olympics.com</a>";
quick.innerHTML = "<b>Olympic Games Tokyo 2020</b><br>July 23, 2021 - August 8, 2021<br><br><p>The 2020 Summer Olympics (Japanese: 2020年夏季オリンピック, Hepburn: Nisen Nijū-nen Kaki Orinpikku), officially the Games of the XXXII Olympiad (第三十二回オリンピック競技大会, Dai Sanjūni-kai Orinpikku Kyōgi Taikai) and branded as Tokyo 2020 (東京2020), is an ongoing international multi-sport event that is currently being held from 23 July to 8 August 2021 in Tokyo, Japan, with some preliminary events beginning on 21 July.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Olympic_rings_without_rims.svg/2880px-Olympic_rings_without_rims.svg.png' style='width:100%; border-radius:8px;'><br><a href='https://www.nbcolympics.com/' target='blank'>Watch on NBC</a><br><a href='https://olympics.com/' target='blank'>Olympics website</a><br><a href='https://www.google.com/search?q=Olympic+Games+Tokyo' target='blank'>More information</a>";
quick.style.visibility = "visible";
} else if (text == "2020 tokyo olympics") {
first.innerHTML = "2020 Tokyo Olympics<br><a href='https://olympics.com' target='blank'>olympics.com</a>";
quick.innerHTML = "<b>Olympic Games Tokyo 2020</b><br>July 23, 2021 - August 8, 2021<br><br><p>The 2020 Summer Olympics (Japanese: 2020年夏季オリンピック, Hepburn: Nisen Nijū-nen Kaki Orinpikku), officially the Games of the XXXII Olympiad (第三十二回オリンピック競技大会, Dai Sanjūni-kai Orinpikku Kyōgi Taikai) and branded as Tokyo 2020 (東京2020), is an ongoing international multi-sport event that is currently being held from 23 July to 8 August 2021 in Tokyo, Japan, with some preliminary events beginning on 21 July.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Olympic_rings_without_rims.svg/2880px-Olympic_rings_without_rims.svg.png' style='width:100%; border-radius:8px;'><br><a href='https://www.nbcolympics.com/' target='blank'>Watch on NBC</a><br><a href='https://olympics.com/' target='blank'>Olympics website</a><br><a href='https://www.google.com/search?q=Olympic+Games+Tokyo' target='blank'>More information</a>";
quick.style.visibility = "visible";
} else if (text == "summer olympics") {
first.innerHTML = "2020 Tokyo Olympics<br><a href='https://olympics.com' target='blank'>olympics.com</a>";
quick.innerHTML = "<b>Olympic Games Tokyo 2020</b><br>July 23, 2021 - August 8, 2021<br><br><p>The 2020 Summer Olympics (Japanese: 2020年夏季オリンピック, Hepburn: Nisen Nijū-nen Kaki Orinpikku), officially the Games of the XXXII Olympiad (第三十二回オリンピック競技大会, Dai Sanjūni-kai Orinpikku Kyōgi Taikai) and branded as Tokyo 2020 (東京2020), is an ongoing international multi-sport event that is currently being held from 23 July to 8 August 2021 in Tokyo, Japan, with some preliminary events beginning on 21 July.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Olympic_rings_without_rims.svg/2880px-Olympic_rings_without_rims.svg.png' style='width:100%; border-radius:8px;'><br><a href='https://www.nbcolympics.com/' target='blank'>Watch on NBC</a><br><a href='https://olympics.com/' target='blank'>Olympics website</a><br><a href='https://www.google.com/search?q=Olympic+Games+Tokyo' target='blank'>More information</a>";
quick.style.visibility = "visible";
} else if (text == "olympic games") {
first.innerHTML = "2020 Tokyo Olympics<br><a href='https://olympics.com' target='blank'>olympics.com</a>";
quick.innerHTML = "<b>Olympic Games Tokyo 2020</b><br>July 23, 2021 - August 8, 2021<br><br><p>The 2020 Summer Olympics (Japanese: 2020年夏季オリンピック, Hepburn: Nisen Nijū-nen Kaki Orinpikku), officially the Games of the XXXII Olympiad (第三十二回オリンピック競技大会, Dai Sanjūni-kai Orinpikku Kyōgi Taikai) and branded as Tokyo 2020 (東京2020), is an ongoing international multi-sport event that is currently being held from 23 July to 8 August 2021 in Tokyo, Japan, with some preliminary events beginning on 21 July.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Olympic_rings_without_rims.svg/2880px-Olympic_rings_without_rims.svg.png' style='width:100%; border-radius:8px;'><br><a href='https://www.nbcolympics.com/' target='blank'>Watch on NBC</a><br><a href='https://olympics.com/' target='blank'>Olympics website</a><br><a href='https://www.google.com/search?q=Olympic+Games+Tokyo' target='blank'>More information</a>";
quick.style.visibility = "visible";
} else if (text == "zimbabwe") {
first.innerHTML = "Zimbabwe - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Zimbabwe</b<br><p>Zimbabwe, officially the Republic of Zimbabwe, is a landlocked country located in Southeast Africa, between the Zambezi and Limpopo Rivers, bordered by South Africa to the south, Botswana to the south-west, Zambia to the north, and Mozambique to the east. The capital and largest city is Harare. The second largest city is Bulawayo. A country of roughly 15 million people, Zimbabwe has 16 official languages, with English, Shona, and Ndebele the most common.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "zambia") {
first.innerHTML = "Zambia - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Zambia</b<br><p>Zambia, which is officially the Republic of Zambia, is a landlocked country at the crossroads of Central, Southern and East Africa. Its neighbors are the Democratic Republic of the Congo to the north, Tanzania to the north-east, Malawi to the east, Mozambique to the southeast, Zimbabwe and Botswana to the south, Namibia to the southwest, and Angola to the west. The capital city of Zambia is Lusaka, located in the south-central part of Zambia. The population is concentrated mainly around Lusaka in the south and the Copperbelt Province to the north, the core economic hubs of the country.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "yemen") {
first.innerHTML = "Yemen - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Yemen</b<br><p>Yemen (Arabic: ٱلْيَمَن), officially the Republic of Yemen, is a country in Western Asia, on the southern end of the Arabian Peninsula. It borders Saudi Arabia to the north and Oman to the northeast and shares maritime borders with Eritrea, Djibouti, and Somalia. It is the second-largest Arab sovereign state in the peninsula, occupying 527,970 square kilometres (203,850 square miles). The coastline stretches for about 2,000 kilometres (1,200 miles). Yemen's constitutionally stated capital, and largest city, is the city of Sanaa, but the city has been under Houthi rebel control since February 2015 as well as Aden, which is also controlled by the Southern Transitional Council since 2018. Its executive administration resides in Riyadh, Saudi Arabia.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "vietnam") {
first.innerHTML = "Vietnam - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Vietnam</b<br><p>Vietnam (Vietnamese: Việt Nam), officially the Socialist Republic of Vietnam, is a country in Southeast Asia. It is located at the eastern edge of the Indochinese Peninsula, and is divided into 58 provinces and five municipalities, covering 331,699 square kilometres, with a population of over 96 million inhabitants, making it the world's sixteenth-most populous country. Vietnam shares borders with China to the north, Laos and Cambodia to the west; whilst maintaining maritime borders with Thailand through the Gulf of Thailand, and the Philippines, Indonesia and Malaysia through the South China Sea. Its capital is Hanoi and its largest city is Ho Chi Minh City (Saigon).</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "venezuela") {
first.innerHTML = "Venezuela - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Venezuela</b<br><p>Venezuela, officially the Bolivarian Republic of Venezuela (Spanish: República Bolivariana de Venezuela), is a country on the northern coast of South America, consisting of a continental landmass and many islands and islets in the Caribbean Sea. It has a territorial extension of 916,445 km2 (353,841 sq mi), and the population of Venezuela was estimated at 28 million in 2019. The capital and largest urban agglomeration is the city of Caracas.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "vatican city") {
first.innerHTML = "Vatican City - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Vatican City</b<br><p>Vatican City, officially the Vatican City State (Italian: Stato della Città del Vaticano; Latin: Status Civitatis Vaticanae), is an independent city state and enclave located within Rome, Italy. The Vatican City State, also known simply as the Vatican, became independent from Italy with the Lateran Treaty (1929), and it is a distinct territory under juriscidtion of the Holy See, itself a sovereign entity of international law, which maintains the city state's temporal, diplomatic, and spiritual independence.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_the_Vatican_City.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "vanuatu") {
first.innerHTML = "Vanuatu - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Vanuatu</b<br><p>Vanuatu is an island country located in the South Pacific Ocean. The archipelago, which is of volcanic origin, is 1,750 kilometres (1,090 mi) east of northern Australia, 540 kilometres (340 mi) northeast of New Caledonia, east of New Guinea, southeast of the Solomon Islands, and west of Fiji.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "uzbekistan") {
first.innerHTML = "Uzbekistan - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Uzbekistan</b<br><p>Uzbekistan, officially the Republic of Uzbekistan (Uzbek: Oʻzbekiston Respublikasi), is a landlocked country in Central Asia. It is surrounded by five countries: Kazakhstan to the north; Kyrgyzstan to the northeast; Tajikistan to the southeast; Afghanistan to the south, Turkmenistan to the south-west. Its capital and largest city is Tashkent. Along with Liechtenstein, it is one of two doubly landlocked countries.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "uruguay") {
first.innerHTML = "Uruguay - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Uruguay</b<br><p>Uruguay, officially the Oriental Republic of Uruguay, is a country in South America. It shares borders with Argentina to its west and southwest and Brazil to its north and northeast; while bordering the Río de la Plata to the south and the Atlantic Ocean to the southeast. Uruguay covers an area of approximately 176,000 square kilometers (68,000 sq mi) and has a population of an estimated 3.51 million, of whom 2 million live in the metropolitan area of its capital and largest city, Montevideo.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "united states") {
first.innerHTML = "United States- Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>United States</b<br><p>:(</p>";
quick.style.visibility = "visible";
} else if (text == "united kingdom") {
first.innerHTML = "United Kingdom- Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>United Kingdom</b<br><p>The United Kingdom of Great Britain and Northern Ireland, commonly known as the United Kingdom (UK) or Britain, is a sovereign country in north-western Europe, off the north-western coast of the European mainland. The United Kingdom includes the island of Great Britain, the north-eastern part of the island of Ireland, and many smaller islands within the British Isles. Northern Ireland shares a land border with the Republic of Ireland. Otherwise, the United Kingdom is surrounded by the Atlantic Ocean, with the North Sea to the east, the English Channel to the south and the Celtic Sea to the south-west, giving it the 12th-longest coastline in the world. The Irish Sea separates Great Britain and Ireland. The total area of the United Kingdom is 93,628 square miles (242,500 km2).</p><br><img src='https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "uk") {
first.innerHTML = "United Kingdom- Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>United Kingdom</b<br><p>The United Kingdom of Great Britain and Northern Ireland, commonly known as the United Kingdom (UK) or Britain, is a sovereign country in north-western Europe, off the north-western coast of the European mainland. The United Kingdom includes the island of Great Britain, the north-eastern part of the island of Ireland, and many smaller islands within the British Isles. Northern Ireland shares a land border with the Republic of Ireland. Otherwise, the United Kingdom is surrounded by the Atlantic Ocean, with the North Sea to the east, the English Channel to the south and the Celtic Sea to the south-west, giving it the 12th-longest coastline in the world. The Irish Sea separates Great Britain and Ireland. The total area of the United Kingdom is 93,628 square miles (242,500 km2).</p><br><img src='https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "england") {
first.innerHTML = "United Kingdom- Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>United Kingdom</b<br><p>The United Kingdom of Great Britain and Northern Ireland, commonly known as the United Kingdom (UK) or Britain, is a sovereign country in north-western Europe, off the north-western coast of the European mainland. The United Kingdom includes the island of Great Britain, the north-eastern part of the island of Ireland, and many smaller islands within the British Isles. Northern Ireland shares a land border with the Republic of Ireland. Otherwise, the United Kingdom is surrounded by the Atlantic Ocean, with the North Sea to the east, the English Channel to the south and the Celtic Sea to the south-west, giving it the 12th-longest coastline in the world. The Irish Sea separates Great Britain and Ireland. The total area of the United Kingdom is 93,628 square miles (242,500 km2).</p><br><img src='https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "britain") {
first.innerHTML = "United Kingdom- Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>United Kingdom</b<br><p>The United Kingdom of Great Britain and Northern Ireland, commonly known as the United Kingdom (UK) or Britain, is a sovereign country in north-western Europe, off the north-western coast of the European mainland. The United Kingdom includes the island of Great Britain, the north-eastern part of the island of Ireland, and many smaller islands within the British Isles. Northern Ireland shares a land border with the Republic of Ireland. Otherwise, the United Kingdom is surrounded by the Atlantic Ocean, with the North Sea to the east, the English Channel to the south and the Celtic Sea to the south-west, giving it the 12th-longest coastline in the world. The Irish Sea separates Great Britain and Ireland. The total area of the United Kingdom is 93,628 square miles (242,500 km2).</p><br><img src='https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "great britain") {
first.innerHTML = "United Kingdom- Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>United Kingdom</b<br><p>The United Kingdom of Great Britain and Northern Ireland, commonly known as the United Kingdom (UK) or Britain, is a sovereign country in north-western Europe, off the north-western coast of the European mainland. The United Kingdom includes the island of Great Britain, the north-eastern part of the island of Ireland, and many smaller islands within the British Isles. Northern Ireland shares a land border with the Republic of Ireland. Otherwise, the United Kingdom is surrounded by the Atlantic Ocean, with the North Sea to the east, the English Channel to the south and the Celtic Sea to the south-west, giving it the 12th-longest coastline in the world. The Irish Sea separates Great Britain and Ireland. The total area of the United Kingdom is 93,628 square miles (242,500 km2).</p><br><img src='https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "united arab emirates") {
first.innerHTML = "United Arab Emirates - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>United Arab Emirates</b<br><p>The United Arab Emirates (UAE; Arabic: الإمارات العربية المتحدة al-ʾImārāt al-ʿArabīyah al-Muttaḥidah), sometimes simply called the Emirates (Arabic: الإمارات al-ʾImārāt), is a country in Western Asia located at the eastern end of the Arabian Peninsula. It borders Oman and Saudi Arabia, and has maritime borders in the Persian Gulf with Qatar and Iran.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "uae") {
first.innerHTML = "United Arab Emirates - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>United Arab Emirates</b<br><p>The United Arab Emirates (UAE; Arabic: الإمارات العربية المتحدة al-ʾImārāt al-ʿArabīyah al-Muttaḥidah), sometimes simply called the Emirates (Arabic: الإمارات al-ʾImārāt), is a country in Western Asia located at the eastern end of the Arabian Peninsula. It borders Oman and Saudi Arabia, and has maritime borders in the Persian Gulf with Qatar and Iran.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "ukraine") {
first.innerHTML = "Ukraine - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Ukraine</b<br><p>Ukraine (Ukrainian: Україна) is a country in Eastern Europe. It is the second-largest country in Europe after Russia, which it borders to the east and north-east. Ukraine also shares borders with Belarus to the north; Poland, Slovakia, and Hungary to the west; Romania and Moldova to the south; and has a coastline along the Sea of Azov and the Black Sea. It spans an area of 603,628 km2 (233,062 sq mi), with a population of 41.4 million, and is the eighth-most populous country in Europe. The nation's capital and largest city is Kyiv.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "uganda") {
first.innerHTML = "Uganda - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Uganda</b<br><p>Uganda (Ugandan Languages: Yuganda), officially the Republic of Uganda (Swahili: Jamhuri ya Uganda), is a landlocked country in East Africa. It is bordered to the east by Kenya, to the north by South Sudan, to the west by the Democratic Republic of the Congo, to the south-west by Rwanda, and to the south by Tanzania. The southern part of the country includes a substantial portion of Lake Victoria, shared with Kenya and Tanzania. Uganda is in the African Great Lakes region. Uganda also lies within the Nile basin and has a varied but generally a modified equatorial climate. It has a population of over 42 million, of which 8.5 million live in the capital and largest city of Kampala.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "tuvalu") {
first.innerHTML = "Tuvalu - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Tuvalu</b<br><p>Tuvalu is an island country in the Polynesian subregion of Oceania in the Pacific Ocean. Its islands are situated about midway between Hawaii and Australia. They lie east-northeast of the Santa Cruz Islands (which belong to the Solomon Islands), northeast of Vanuatu, southeast of Nauru, south of Kiribati, west of Tokelau, northwest of Samoa and Wallis and Futuna, and north of Fiji. Tuvalu is composed of three reef islands and six atolls. They are spread out between the latitude of 5° and 10° south, and between the longitude of 176° and 180°. They lie west of the International Date Line. Tuvalu has a population of 10,507. The total land area of the islands of Tuvalu is 26 square kilometres (10 sq mi).</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "turkmenistan") {
first.innerHTML = "Turkmenistan - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Turkmenistan</b<br><p>Turkmenistan, also known as Turkmenia, is a country in Central Asia, bordered by Kazakhstan to the northwest, Uzbekistan to the north, east and northeast, Afghanistan to the southeast, Iran to the south and southwest and the Caspian Sea to the west. Ashgabat is the capital and largest city of the country. The population of the country is about 6 million, the lowest of the Central Asian republics. Turkmenistan is one of the most sparsely populated nations in Asia. Citizens of Turkmenistan are known as Turkmenistanis, Turkmenians or Turkmens.</p><br><a href='https://turkmenistan.gov.tm/tk' target='_blank'>Government website</a><br><img src='https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "turkey") {
first.innerHTML = "Turkey - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Turkey</b<br><p>Turkey (Turkish: Türkiye), officially the Republic of Turkey, is a country straddling Western Asia and Southeast Europe. It shares borders with Greece and Bulgaria to the northwest; the Black Sea to the north; Georgia to the northeast; Armenia, Azerbaijan, and Iran to the east; Iraq to the southeast; Syria and the Mediterranean Sea to the south; and the Aegean Sea to the west. Turks form the vast majority of the nation's population and Kurds are the largest minority. Its capital is Ankara while its largest city and financial center is Istanbul.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "tunisia") {
first.innerHTML = "Tunisia - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Tunisia</b<br><p>Tunisia, officially the Republic of Tunisia, is the northernmost country in Africa. It is a part of the Maghreb region of North Africa, and is bordered by Algeria to the west and southwest, Libya to the southeast, and the Mediterranean Sea to the north and east; covering 163,610 km2 (63,170 sq mi), with a population of 11 million. It contains the eastern end of the Atlas Mountains and the northern reaches of the Sahara desert, with much of its remaining territory arable land. Its 1,300 km (810 mi) of coastline include the African conjunction of the western and eastern parts of the Mediterranean Basin.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "trinidad and tobago") {
first.innerHTML = "Trinidad and Tobago - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Trinidad and Tobago</b<br><p>Trinidad and Tobago, officially the Republic of Trinidad and Tobago, is the southernmost island country in the Caribbean and is known for its fossil-fuel wealth. Consisting of the main islands Trinidad and Tobago, and numerous much smaller islands, it is situated 130 kilometres (81 miles) south of Grenada and 11 kilometres (6.8 miles) off the coast of northeastern Venezuela. It shares maritime boundaries with Barbados to the northeast, Grenada to the northwest and Venezuela to the south and west.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "tonga") {
first.innerHTML = "Tonga - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Tonga</b<br><p>Tonga, officially named the Kingdom of Tonga (Tongan: Puleʻanga Fakatuʻi ʻo Tonga), is a Polynesian country, and also an archipelago comprising 169 islands, of which 36 are inhabited.[1] The archipelago's total surface area is about 750 square kilometres (290 sq mi) scattered over 700,000 square kilometres (270,000 sq mi) of the southern Pacific Ocean. As of 2016, Tonga had a population of 100,651, 70% of whom resided on the main island, Tongatapu.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "transnistria") {
first.innerHTML = "Transnistria - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Transnistria</b<br><p>Transnistria, officially the Pridnestrovian Moldavian Republic, is a breakaway state in the narrow strip of land between the river Dniester and the Ukrainian border that is internationally recognized as part of Moldova. Its capital and largest city is Tiraspol. Transnistria has been recognised by only three other mostly unrecognised breakaway states: Abkhazia, Artsakh, and South Ossetia. Transnistria is designated by the Republic of Moldova as the Transnistria autonomous territorial unit with special legal status (Romanian: Unitatea teritorială autonomă cu statut juridic special Transnistria).</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Transnistria_%28state%29.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "togo") {
first.innerHTML = "Togo - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Togo</b<br><p>Togo, officially the Togolese Republic, is a country in West Africa. It is bordered by Ghana to the west, Benin to the east and Burkina Faso to the north. The country extends south to the Gulf of Guinea, where its capital and largest city Lomé is located. Togo covers 57,000 square kilometres (22,008 square miles), making it one of the smallest countries in Africa, with a population of approximately 8 million, as well as one of the narrowest countries in the world with a width of less than 115 km (71 mi) between Ghana and its slightly larger eastern neighbor, Benin.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "thailand") {
first.innerHTML = "Thailand - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Thailand</b<br><p>Thailand (Thai: ประเทศไทย), officially the Kingdom of Thailand, is a country in Southeast Asia. It is located at the centre of the Indochinese Peninsula, spanning 513,120 square kilometres (198,120 sq mi), with a population of over 66 million people. Thailand is bordered to the north by Myanmar and Laos, to the east by Laos and Cambodia, to the south by the Gulf of Thailand and Malaysia, and to the west by the Andaman Sea and the southern extremity of Myanmar. </p><br><img src='https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "tanzania") {
first.innerHTML = "Tanzania - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Tanzania</b<br><p>Tanzania, officially the United Republic of Tanzania (Swahili: Jamhuri ya Muungano wa Tanzania), is a country in East Africa within the African Great Lakes region. It borders Uganda to the north; Kenya to the northeast; Comoro Islands and the Indian Ocean to the east; Mozambique and Malawi to the south; Zambia to the southwest; and Rwanda, Burundi, and the Democratic Republic of the Congo to the west. Mount Kilimanjaro, Africa's highest mountain, is in northeastern Tanzania.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "tajikistan") {
first.innerHTML = "Tajikistan - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Tajikistan</b<br><p>Tajikistan, (Tajik: Тоҷикистон), officially the Republic of Tajikistan (Tajik: Ҷумҳурии Тоҷикистон), is a landlocked country in Central Asia with an area of 143,100 km2 (55,300 sq mi) and an estimated population of 9,537,645 people. Its capital and largest city is Dushanbe. It is bordered by Afghanistan to the south, Uzbekistan to the west, Kyrgyzstan to the north and China to the east. The traditional homelands of the Tajik people include present-day Tajikistan as well as parts of Afghanistan and Uzbekistan.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "taiwan") {
first.innerHTML = "Taiwan - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Taiwan</b<br><p>Taiwan, officially the Republic of China, is a country in East Asia. It shares maritime borders with the People's Republic of China to the northwest, Japan to the northeast, and the Philippines to the south. The main island of Taiwan has an area of 35,808 square kilometres (13,826 sq mi), with mountain ranges dominating the eastern two-thirds and plains in the western third, where its highly urbanised population is concentrated. The capital is Taipei, which, along with New Taipei and Keelung, forms the largest metropolitan area of Taiwan. Other major cities include Kaohsiung, Taichung, Tainan and Taoyuan. With 23.57 million inhabitants, Taiwan is among the most densely populated countries in the world.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "syria") {
first.innerHTML = "Syria - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Syria</b<br><p>Syria (Arabic: سُورِيَا), officially the Syrian Arab Republic (Arabic: ٱلْجُمْهُورِيَّةُ ٱلْعَرَبِيَّةُ ٱلسُّورِيَّةُ), is a country in Western Asia, bordering Lebanon to the southwest, the Mediterranean Sea to the west, Turkey to the north, Iraq to the east, Jordan to the south, and Israel to the southwest. Its capital and largest city is Damascus.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "switzerland") {
first.innerHTML = "Switzerland - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Switzerland</b<br><p>Switzerland, officially the Swiss Confederation, is a landlocked country situated at the confluence of Western, Central and Southern Europe. It is a federal republic composed of 26 cantons, with federal authorities based in Bern. Switzerland is bordered by Italy to the south, France to the west, Germany to the north and Austria and Liechtenstein to the east. It is geographically divided among the Swiss Plateau, the Alps and the Jura, spanning a total area of 41,285 km2 (15,940 sq mi) and land area of 39,997 km2 (15,443 sq mi).</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "sweden") {
first.innerHTML = "Sweden - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Sweden</b<br><p>Sweden, officially the Kingdom of Sweden (Swedish: Konungariket Sverige), is a Nordic country in Northern Europe. It borders Norway to the west and north, Finland to the east, and is connected to Denmark in the southwest by a bridge-tunnel across the Öresund Strait. At 450,295 square kilometres (173,860 sq mi), Sweden is the largest country in Northern Europe, the third-largest country in the European Union, and the fifth largest country in Europe. The capital and largest city is Stockholm.</p><br><img src='https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "suriname") {
first.innerHTML = "Suriname - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Suriname</b<br><p>Suriname or Surinam, officially known as the Republic of Suriname (Dutch: Republiek Suriname), is a country on the northeastern Atlantic coast of South America. It is bordered by the Atlantic Ocean to the north, French Guiana to the east, Guyana to the west, and Brazil to the south. At just under 165,000 square kilometers (64,000 square miles), it is the smallest sovereign state in South America. Suriname has a population of approximately 575,990, most of whom live on the country's north coast, in and around the capital and largest city, Paramaribo.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "sudan") {
first.innerHTML = "Sudan - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Sudan</b<br><p>Sudan (Arabic: السودان), officially the Republic of the Sudan (Arabic: جمهورية السودان), is a country in Northeast Africa. It is bordered by Egypt to the north, Libya to the northwest, Chad to the west, the Central African Republic to the southwest, South Sudan to the south, Ethiopia to the southeast, Eritrea to the east, and the Red Sea to the northeast. Sudan has a population of 44.91 million people as of 2021 and occupies 1,886,068 square kilometres (728,215 square miles), making it Africa's third-largest country by area and also the third-largest by area in the Arab league. It was also the largest country by area in Africa and the Arab league until the secession of South Sudan in 2011, since which both titles have been held by Algeria. Its capital is Khartoum, while its largest city is Omdurman.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "sri lanka") {
first.innerHTML = "Sri Lanka - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Sri Lanka</b<br><p>Sri Lanka (Sinhala: ශ්‍රී ලංකාව; Tamil: இலங்கை), formerly known as Ceylon, and officially the Democratic Socialist Republic of Sri Lanka, is an island country in South Asia. It lies in the Indian Ocean, southwest of the Bay of Bengal, and southeast of the Arabian Sea; it is separated from the Indian subcontinent by the Gulf of Mannar and the Palk Strait, but shares a maritime border with the Indian state of Tamil Nadu. Sri Jayawardenepura Kotte is its legislative capital, and Colombo is its largest city and financial center.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "spain") {
first.innerHTML = "Spain - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Spain</b<br><p>Spain (Spanish: España) is a country in Southwestern Europe with some pockets of territory in Africa across the Strait of Gibraltar and offshore in the Atlantic Ocean. Its continental European territory is situated on the Iberian Peninsula and Its territory also includes two archipelagos: the Canary Islands off the coast of North Africa, and the Balearic Islands in the Mediterranean Sea. The African exclaves of Ceuta, Melilla, and Peñón de Vélez de la Gomera make Spain the only European country to have continental African territories.[h] Several small islands in the Alboran Sea are also part of Spanish territory. The country's mainland is bordered to the south and east by the Mediterranean Sea; to the north and northeast by France, Andorra, and the Bay of Biscay; and to the west and northwest by Portugal and the Atlantic Ocean, respectively.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/8/89/Bandera_de_Espa%C3%B1a.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "south sudan") {
first.innerHTML = "South Sudan - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>South Sudan</b<br><p>South Sudan, officially known as the Republic of South Sudan, is a landlocked country in east/central Africa. It is bordered to the east by Ethiopia, to the north by Sudan, to the west by the Central African Republic, to the southwest by Democratic Republic of the Congo, to the south by Uganda and to the southeast by Kenya. It has a population of 11.06 million, of which 525,953 live in the capital and largest city Juba.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/7/7a/Flag_of_South_Sudan.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "south ossetia") {
first.innerHTML = "South Ossetia - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>South Ossetia</b<br><p>South Ossetia, officially the Republic of South Ossetia, the State of Alania, or the Tskhinvali Region, is a de facto state in the South Caucasus recognised by most countries as part of Georgia. It has an officially stated population of just over 53,000 people, who live in an area of 3,900 km2, south of the Russian Caucasus, with 30,000 living in Tskhinvali. The separatist polity, Republic of South Ossetia (or the State of Alania), is recognized as a state by Russia, Venezuela, Nicaragua, Nauru, and Syria. While Georgia lacks control over South Ossetia, the Georgian government and most members of the United Nations consider the territory part of Georgia.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/1/12/Flag_of_South_Ossetia.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "south korea") {
first.innerHTML = "South Korea - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>South Korea</b<br><p>South Korea, officially the Republic of Korea (Korean: 대한민국), is a country in East Asia, constituting the southern part of the Korean Peninsula, and sharing a land border with North Korea. About 25 million people, around half of the country's population of 51 million, live in the Seoul Capital Area.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "south africa") {
first.innerHTML = "South Africa - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>South Africa</b<br><p>South Africa, officially the Republic of South Africa (RSA), is a country in Southern Africa. With over 60 million people, it is the world's 23rd-most populous nation and covers an area of 1,221,037 square kilometres (471,445 square miles). South Africa has three capital cities: executive Pretoria, judicial Bloemfontein and legislative Cape Town. The largest city is Johannesburg.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "somaliland") {
first.innerHTML = "Somaliland - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Somaliland</b<br><p>Somaliland (Somali: Somaliland; Arabic: صوماليلاند), officially the Republic of Somaliland (Somali: Jamhuuriyadda Soomaaliland, Arabic: جمهورية صوماليلاند), is an unrecognised sovereign state in the Horn of Africa, internationally considered to be part of Somalia. Somaliland lies in the Horn of Africa, on the southern coast of the Gulf of Aden. It is bordered by Djibouti to the northwest, Ethiopia to the south and west, and Somalia to the east. Its claimed territory has an area of 176,120 square kilometres (68,000 sq mi), with approximately 5.7 million residents in 2021. The capital and largest city is Hargeisa. The government of Somaliland regards itself as the successor state to British Somaliland, which, as the briefly independent State of Somaliland, united in 1960 with the Trust Territory of Somaliland (the former Italian Somaliland) to form the Somali Republic.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/4/4d/Flag_of_Somaliland.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "somalia") {
first.innerHTML = "Somalia - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Somalia</b<br><p>Somalia, officially the Federal Republic of Somalia, is a country in the Horn of Africa. It is bordered by Ethiopia to the west, Djibouti to the Northwest, the Gulf of Aden to the north, the Indian Ocean to the east, and Kenya to the southwest. Somalia has the longest coastline on Africa's mainland. Its terrain consists mainly of plateaus, plains, and highlands. Hot conditions prevail year-round, with periodic monsoon winds and irregular rainfall. Somalia has an estimated population of around 15 million, of which over 2 million live in the capital and largest city Mogadishu, and has been described as Africa's most culturally homogeneous country.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "solomon islands") {
first.innerHTML = "Solomon Islands - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Solomon Islands</b<br><p>Solomon Islands is a sovereign country consisting of six major islands and over 900 smaller islands in Oceania, to the east of Papua New Guinea and northwest of Vanuatu. It has a land area of 28,400 square kilometres (11,000 sq mi), and a population of 652,858. Its capital, Honiara, is located on the island of Guadalcanal. The country takes its name from the Solomon Islands archipelago, which is a collection of Melanesian islands that also includes the North Solomon Islands.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "slovenia") {
first.innerHTML = "Slovenia - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Slovenia</b<br><p>Slovenia (Slovene: Slovenija) officially the Republic of Slovenia, is a country in Central Europe. It is bordered by Italy to the west, Austria to the north, Hungary to the northeast, Croatia to the southeast, and the Adriatic Sea to the southwest. Slovenia is mostly mountainous and forested, covers 20,271 square kilometers (7,827 sq mi), and has a population of 2.1 million, of which 500,000 live in the capital and largest city Ljubljana. Slovenes form the vast majority of the country's population, while Serbs are the largest minority. Slovene, a South Slavic language, is the official language. It has one of the lowest rates of income inequality in the world.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "slovakia") {
first.innerHTML = "Slovakia - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Slovakia</b<br><p>Slovakia (Slovak: Slovensko), officially the Slovak Republic (Slovak: Slovenská republika), is a landlocked country in Central Europe. It is bordered by Poland to the north, Ukraine to the east, Hungary to the south, Austria to the southwest, and the Czech Republic to the northwest. Slovakia's mostly mountainous territory spans about 49,000 square kilometres (19,000 sq mi), with a population of over 5.4 million. The capital and largest city is Bratislava, while the second largest city is Košice.</p><br><img src='https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text == "singapore") {
first.innerHTML = "Singapore - Wikipedia<br><a href='https://wikipedia.org/wiki/" + text + "' target='blank'>wikipedia.org</a>";
quick.innerHTML = "<b>Singapore</b<br><p>Singapore, officially the Republic of Singapore, is a sovereign island city-state in maritime Southeast Asia. It lies about one degree of latitude (137 kilometres or 85 miles) north of the equator, off the southern tip of the Malay Peninsula, bordering the Straits of Malacca to the west, the Riau Islands (Indonesia) to the south, and the South China Sea to the east. The country's territory is composed of one main island, 63 satellite islands and islets, and one outlying islet, the combined area of which has increased by 25% since the country's independence as a result of extensive land reclamation projects. It has the second greatest population density in the world. </p><br><img src='https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg' style='width:100%; border-radius:8px;'>";
quick.style.visibility = "visible";
} else if (text.split(" ")[0] == "google") {
first.innerHTML = text + " - official site<br><a href='https://" + text.split("google ")[1] + ".google.com' target='_blank'>" + text.split("google ")[1] + ".google.com</a>";
quick.innerHTML = text + " - official site<br><br><a href='https://" + text.split("google ")[1] + ".google.com' target='_blank'>" + text.split("google ")[1] + ".google.com</a>";
quick.style.visibility = "visible";
} else if (text.split(" ")[0] == "yandex") {
first.innerHTML = text + " - official site<br><a href='https://" + text.split("yandex ")[1] + ".yandex.com' target='_blank'>" + text.split("yandex ")[1] + ".yandex.com</a>";
quick.innerHTML = text + " - official site<br><br><a href='https://" + text.split("yandex ")[1] + ".yandex.com' target='_blank'>" + text.split("yandex ")[1] + ".yandex.com</a>";
quick.style.visibility = "visible";
} else if (text.split(" ")[0] == "bing") {
first.innerHTML = text + " - official site<br><a href='https://" + text.split("bing ")[1] + ".bing.com' target='_blank'>" + text.split("bing ")[1] + ".bing.com</a>";
quick.innerHTML = text + " - official site<br><br><a href='https://" + text.split("bing ")[1] + ".bing.com' target='_blank'>" + text.split("bing ")[1] + ".bing.com</a>";
quick.style.visibility = "visible";
} else if (text.split(" ")[0] == "yahoo") {
first.innerHTML = text + " - official site<br><a href='https://" + text.split("yahoo ")[1] + ".yahoo.com' target='_blank'>" + text.split("yahoo ")[1] + ".yahoo.com</a>";
quick.innerHTML = text + " - official site<br><br><a href='https://" + text.split("yahoo ")[1] + ".yahoo.com' target='_blank'>" + text.split("yahoo ")[1] + ".yahoo.com</a>";
quick.style.visibility = "visible";
} else if (query.length > 30) {
quick.innerHTML = "<b>" + query + "</b><br><p>Galaxy is working to have better results and quick answers available for popular topics. This is currently not available for your search.</p>";
quick.style.visibility = "visible";
} else if (text.search("near me") > -1) {
getLocation();
quick.style.visibility = "visible";
} else if (text.search(" ") == -1) {
first.innerHTML = text + ".com - suggested website<br><a href='https://" + text + ".com' title='This link has not been verified and may be unsafe'>" + text + ".com</a>";
quick.innerHTML = "<b>Galaxy is working on having better results</b><br><p style='text-align:center;'><span class='material-icons' style='color:#5765f2;'>feedback</span></p>The first result has not been checked and may not actually lead to a website.";
quick.style.visibility = "visible";
} else {
quick.style.visibility = "hidden";
}
}
setquickAnswer();
